const GIS=["LAYER","PIXEL","SCALE","FIELD","ATLAS","NORTH","RIDGE","TILES","PATHS","DATUM","PROXY","DUNES","LABEL","TOKEN","DRONE","BYTES","ANGLE","ORBIT","RANGE","BANDS","ROUTE","CACHE","LINES","INSET","LIDAR","ALIAS","MODEL","RADAR","TRAIL","MERGE","NTRIP","BLOCK","RIVER","ERASE","URBAN","ASCII","STACK","METRE","UNION","FRAME","FLOOD","SPLIT","EARTH","BASIN","EDGES","FOCAL","SHADE","TITLE","LASER","SCENE","RINGS","TRACE","TRACK","NODES","SPACE","HATCH","INDEX","ROADS","LEVEL","FALSE","QUERY","SOLVE","RURAL","COLOR","STORM","PLANE","VALUE","POINT","TIDES","SHARE","ARRAY","ICONS","PLACE","VIEWS","IMAGE","LOCUS","FLOAT","WATER","FAULT","STORY","TABLE","STAKE","CLOUD","STORE","COAST","BREAK","SHORE","PHOTO","TOOLS","WORLD"];
const PLACES=["Levin","Bluff","Ōrewa","Clyde","Hāwea","Taupō","Clive","Ngawi","Kumeū","Waiau","Anama","Ohawe","Otago","Maunu","Haast","Waotu","Onawe","Waipu","Lyell","Homai","Māhia","Omori","Ōhope","Waipā","Okitū","Uruti","Otira","Mōkau","Epsom","Pātea","Orini","Kawau","Opawa","Aotea","Ōkato","Omaka","Pūhoi","Omanu","Tihoi","Purau","Kaiti","Tūhua","Ōmaha","Kelso","Pouto","Waihō","Stoke","Leigh","Drury","Ōreti","Kaihu","Opito","Ranui","Māpua","Ōtaki","Ruato","Ōhura","Hahei","Matua","Ōkura","Waihi","Opuha","Matiu","Turua","Kauri","Ōrari","Ōtara","Taipa","Ophir","Koutu","Warea","Oteha","Tīrau","Hinds","Ngaio","Raoul","Paroa","Bulls","Judea","Opoho","Omata","Ōpaki","Ohoka","Epuni","Oropi","Ōpihi","Tīnui","Athol","Waimā","Kurow"];
const CATEGORY={"HATCH":"Cartography","LAYER":"Cartography","INSET":"Cartography","LABEL":"Cartography","COLOR":"Cartography","SCALE":"Cartography","SHADE":"Cartography","ATLAS":"Cartography","DRONE":"Imagery","FALSE":"Imagery","LASER":"Imagery","RADAR":"Imagery","BANDS":"Imagery","PIXEL":"Imagery","FRAME":"Imagery","LIDAR":"Imagery","CLOUD":"Imagery","PHOTO":"Imagery","ORBIT":"Imagery","IMAGE":"Imagery","INDEX":"Data","FIELD":"Data","QUERY":"Data","ARRAY":"Data","TABLE":"Data","BYTES":"Data","VALUE":"Data","ALIAS":"Data","ASCII":"Data","FLOAT":"Data","STORE":"Data","DATUM":"Positioning","NORTH":"Positioning","PLANE":"Positioning","STAKE":"Positioning","LOCUS":"Positioning","LEVEL":"Positioning","METRE":"Positioning","ANGLE":"Positioning","NTRIP":"Positioning","CACHE":"Web GIS","ICONS":"Web GIS","STORY":"Web GIS","SCENE":"Web GIS","VIEWS":"Web GIS","TILES":"Web GIS","SHARE":"Web GIS","PROXY":"Web GIS","TOKEN":"Web GIS","SPLIT":"Analysis","FOCAL":"Analysis","MODEL":"Analysis","TRACE":"Analysis","ERASE":"Analysis","STACK":"Analysis","TOOLS":"Analysis","BREAK":"Analysis","EDGES":"Analysis","ROUTE":"Analysis","PATHS":"Analysis","RANGE":"Analysis","MERGE":"Analysis","SOLVE":"Analysis","UNION":"Analysis","POINT":"Geometry","NODES":"Geometry","LINES":"Geometry","RINGS":"Geometry","RIDGE":"Terrain","DUNES":"Terrain","EARTH":"Terrain","BASIN":"Terrain","TRAIL":"Fieldwork","TRACK":"Fieldwork","TITLE":"Land","BLOCK":"Land","PLACE":"Land","STORM":"Hazards","FLOOD":"Hazards","FAULT":"Hazards","URBAN":"Geography","SPACE":"Geography","WATER":"Geography","ROADS":"Geography","WORLD":"Geography","RURAL":"Geography","TIDES":"Geography","RIVER":"Geography","COAST":"Geography","SHORE":"Geography"};
const SPECIAL_GIS={"LAYER":["Mapping","A way to organise related spatial information.","A GIS project often stacks many of these on top of one another."],"PIXEL":["Imagery","The smallest addressable part of a raster image.","Zoom far enough into aerial imagery and you begin to see these squares."],"SCALE":["Cartography","A relationship between map distance and real-world distance.","A map at 1:50,000 is describing this."],"FIELD":["Data","A named place for one attribute in a table.","In an attribute table, this is a column rather than a row."],"ATLAS":["Cartography","A collection of maps.","Traditionally a book of maps, now just as likely to be digital."],"NORTH":["Positioning","A cardinal direction used throughout mapping.","The direction behind the N in an NZTM coordinate pair."]};
const SPECIAL_PLACE={"LEVIN":["Settlement","A town in the Horowhenua district.","This town lies north of Wellington on State Highway 1."],"BLUFF":["Southland","A southern port town.","It is famous as the southern end of State Highway 1."],"OREWA":["Coast","A coastal settlement north of Auckland.","Its long beach sits on the Hibiscus Coast."],"CLYDE":["Central Otago","A historic town in Central Otago.","It sits beside the Clutha / Mata-Au near the Clyde Dam."],"HAWEA":["Lakes","An Otago place associated with a major lake.","Lake Hāwea and its settlement share this name."],"TAUPO":["Water","A major lake and settlement in the central North Island.","New Zealand’s largest lake by surface area shares this name with the town on its shore."]};
const START='2026-08-18';
const ZONE='Pacific/Auckland';

function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z]/g,'')}
function isoDate(d){return d.toISOString().slice(0,10)}
function businessDates(){const out=[];let d=new Date(START+'T00:00:00Z');while(out.length<90){const w=d.getUTCDay();if(w!==0&&w!==6)out.push(isoDate(d));d=new Date(d.getTime()+86400000)}return out}
const DATES=businessDates();
function local9ToUtc(dateStr){const [y,m,d]=dateStr.split('-').map(Number);const target=Date.UTC(y,m-1,d,9,0,0);let guess=target;for(let i=0;i<3;i++){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:ZONE,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(guess)).filter(p=>p.type!=='literal').map(p=>[p.type,p.value]));const represented=Date.UTC(+parts.year,+parts.month-1,+parts.day,+parts.hour,+parts.minute,+parts.second);guess-=represented-target}return guess}
const RELEASES=DATES.map(d=>[d,local9ToUtc(d)]);
function currentPuzzle(now=Date.now()){let i=-1;for(let n=0;n<RELEASES.length;n++){if(RELEASES[n][1]<=now)i=n;else break}return i}
function shapeHint(n,prefix){const vowels=(n.match(/[AEIOU]/g)||[]).length;const repeats=new Set(n).size<n.length?' It contains a repeated letter.':'';return `${prefix} It has ${vowels} vowel${vowels===1?'':'s'}.${repeats}`}
function meta(mode,i){if(i<0||i>=90)return null;const answer=mode==='place'?PLACES[i]:GIS[i];const n=norm(answer);if(mode==='place'){const sp=SPECIAL_PLACE[n];return{answer:n,display:answer,theme:sp?.[0]||'Aotearoa place',hint2:sp?.[1]||shapeHint(n,'A five-letter place name from Aotearoa New Zealand.'),hint3:sp?.[2]||`Starts with ${n[0]} and ends with ${n[4]}.`,featureType:sp?.[0]||'Place'}}const sg=SPECIAL_GIS[n];const theme=sg?.[0]||CATEGORY[n]||'Geospatial';return{answer:n,display:n,theme,hint2:sg?.[1]||shapeHint(n,`A five-letter term used in ${theme.toLowerCase()}.`),hint3:sg?.[2]||`Starts with ${n[0]} and ends with ${n[4]}.`}}
function evaluate(guess,answer){const g=[...guess],a=[...answer],out=Array(5).fill('absent'),left={};for(let i=0;i<5;i++){if(g[i]===a[i])out[i]='correct';else left[a[i]]=(left[a[i]]||0)+1}for(let i=0;i<5;i++){if(out[i]==='correct')continue;if(left[g[i]]>0){out[i]='present';left[g[i]]--}}return out}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
async function api(request,url){if(url.searchParams.get('calendar')==='1')return json({releases:RELEASES.map(([d,t])=>[d,new Date(t).toISOString()])});const mode=url.searchParams.get('mode')==='place'?'place':'gis',i=currentPuzzle();if(request.method==='GET'){if(i<0)return json({active:false,total:90,nextRelease:new Date(RELEASES[0][1]).toISOString(),nextDate:DATES[0],mode});const p=meta(mode,i),attempts=Math.max(0,Number(url.searchParams.get('attempts')||0));return json({active:true,id:i+1,date:DATES[i],total:90,nextRelease:i<89?new Date(RELEASES[i+1][1]).toISOString():null,nextDate:i<89?DATES[i+1]:null,mode,theme:p.theme,...(attempts>=4?{hint2:p.hint2}:{}),...(attempts>=5?{hint3:p.hint3}:{}),...(mode==='place'?{featureType:p.featureType}:{})})}if(request.method!=='POST')return json({error:'Method not allowed'},405);let body;try{body=await request.json()}catch{return json({error:'Invalid request'},400)};const bm=body.mode==='place'?'place':'gis';if(i<0)return json({error:'No active puzzle'},409);const p=meta(bm,i),attempt=Math.max(0,Number(body.attempt||0));if(body.reveal)return json({answer:p.display,theme:p.theme,hint2:p.hint2,hint3:p.hint3});const guess=norm(body.guess);if(guess.length!==5)return json({error:'Enter five letters'},400);const correct=guess===p.answer;return json({correct,evaluation:evaluate(guess,p.answer),theme:p.theme,...(attempt>=4?{hint2:p.hint2}:{}),...(attempt>=5?{hint3:p.hint3}:{}),...(correct?{answer:p.display}:{})})}
export default{async fetch(request,env){const url=new URL(request.url);try{if(url.pathname==='/api/puzzle')return await api(request,url);if(url.pathname==='/place'||url.pathname==='/place/'){const u=new URL(request.url);u.pathname='/place.html';return env.ASSETS.fetch(new Request(u,request))}return env.ASSETS.fetch(request)}catch(err){console.error(JSON.stringify({event:'request_error',path:url.pathname,message:String(err?.message||err)}));return new Response('Internal error',{status:500})}}};
export{norm,evaluate,currentPuzzle,local9ToUtc,meta,DATES,RELEASES};
